name: CI/CD Pipeline for Smart Collect (Pull Request)

on:
  pull_request:
    branches:
      - master  # Trigger on PRs targeting the master branch
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Merge the PR
      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Merging the PR..."
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
      
      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # pip install -r requirements.txt
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chrome-linux64.zip" -P /tmp
          unzip /tmp/chrome-linux64.zip -d /tmp
          sudo mv /tmp/chrome-linux64 /opt/google-chrome
          sudo ln -s /opt/google-chrome/chrome /usr/local/bin/google-chrome
          google-chrome --version

      # Step 7: Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chromedriver-linux64.zip" -P /tmp
          unzip /tmp/chromedriver-linux64.zip -d /tmp
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      # Step 8: Run Selenium Tests
      - name: Run Selenium Tests
        env: 
          GIT_USERNAME: Gaurimusmade
          GIT_EMAIL: gaurimusmade27@gmail.com
        run: |
          echo "Running Selenium tests..."
          python main.py

      # Step 9: Revert the PR if Selenium Tests Fail
      - name: Revert PR if tests failed
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Tests failed. Reverting the merged PR..."

          # Revert the merge commit
          git fetch origin master
          git checkout master
          git revert -m 1 $(git log -n 1 --pretty=format:"%H") --no-edit
          git push origin master
