name: CI/CD Pipeline for Smart Collect

on:
  push:
    branches:
      - master   # Trigger on pushes to the development branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Selenium dependencies
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install ChromeDriver (Specific Version)
        run: |
          # Update apt and install necessary dependencies
          sudo apt-get update
          sudo apt-get install -y wget unzip
      
          # Set the specific ChromeDriver version
          CHROMEDRIVER_VERSION="131.0.6778.205"
          
          # Debug: Print the URL being fetched
          echo "Downloading ChromeDriver version ${CHROMEDRIVER_VERSION}..."
      
          # Use verbose mode for wget to debug the error
          wget -v "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P /tmp
          
          # Check if wget was successful
          if [ $? -ne 0 ]; then
            echo "Error: Failed to download ChromeDriver"
            exit 1
          fi
          
          # Unzip ChromeDriver to the correct location
          unzip /tmp/chromedriver_linux64.zip -d /usr/local/bin/
          
          # Clean up
          rm /tmp/chromedriver_linux64.zip
          
          # Verify installation by printing the ChromeDriver version
          /usr/local/bin/chromedriver --version


      # Step 4: Run Selenium tests
      - name: Run Selenium Tests and Generate Report
        run: |
          python main.py 
